### ISSUE TITLE
Sequelizer not working

### ISSUE THREAD

**Issue by PandavaCharan** [andyforever/sequelizer#3]
I tried with your example, and able to view the UI.
But when i click on Export button, nothing is happening. No Models are generated.
Can you please look into this issue ASAP, as i have finish this task with high Priority.

Thanks,
Charan

**Comment by andyforever** [comment]
which Database type did you choose? MySQL? Or others?

**Comment by PandavaCharan** [comment]
Thank you for your response.
I am using Postgres Database.

Charan.

**Comment by andyforever** [comment]
Maybe you can download the sourcecode and open the devtools for more information.
 ````javascript
 //main.js
// Open the DevTools.
mainWindow.webContents.openDevTools()
````

**Comment by danysz** [comment]
I had the same problem and I figured out the issue.

It's related to the version of the "dependency" of "pg" - moved back to 6.1.2 and everything is now working fine. For 7.x they moved to promises.

**Comment by andyforever** [comment]
@danysz Thanks.I will move pg version back to 6.1.2
