### ISSUE TITLE
Error: Please install tedious package manually

### ISSUE THREAD

**Issue by CopyJosh** [andyforever/sequelizer#4]
First time install, and received the error when trying to run Sequelizer against a Microsoft SQL database. I ran

``` npm install tedious --save-dev ```

and it resolved the issue.

Not sure if it was a goof on the install, but sharing for posterity. 

Edit: on Mac, and downloadable app didn't work at all. Assuming perhaps similar error, but global install of tedious didn't resolve, for what it's worth

**Comment by andyforever** [comment]
Thanks, I am working on it

**Comment by andyforever** [comment]
@CopyJosh Sorry I cannot reproduce your problem. May be it's the system environment reason. Now I remove the download link from this repo.

**Comment by mostafa8026** [comment]
I have the similar problem when using the pkg (npm pacckager) and create a exe package.
reproduce steps:
1- create a simple node application with tedious
2- npm install -g pkg
3- pkg -t win-x64 index.js -o apptedious
4- apptedious
